artifact_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://archive.ics.uci.edu/static/public/2/adult.zip
  zipped_local_dir: artifacts/data_ingestion/adult.zip
  unzip_dir: artifacts/data