channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.3.1
- pip:
  - mlflow==2.11.0
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.1.4
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.11.4
  - xgboost==2.0.3
name: mlflow-env
